### ISSUE TITLE
test  error at pet-shop tutorial

### ISSUE THREAD

**Issue by hatshu** [trufflesuite/trufflesuite.com#271]
im using visual code studio
windows 10
Truffle v5.0.0 (core: 5.0.0)
Solidity v0.5.0 (solc-js)
Node v10.15.0
ganache gui

I can compile the project
I can migrate the project 
but i can't pass test.  I have this output:
PS D:\DESARROLLO\Servicechain.git\servicechain\pet-shop-tutorial> truffle testUsing network 'development'.

Compiling .\test\TestAdoption.sol...

  TestAdoption
    1) "before all" hook: prepare suite

  0 passing (9s)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     Error: Could not find artifacts for /D/DESARROLLO/Servicechain.git/servicechain/pet-shop-tutorial/contracts/Adoption.sol from any sources
      at Resolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at dependency_paths.forEach.dependency_path (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by hatshu** [comment]
Yes I have this problem yet¡¡¡¡

**Comment by hatshu** [comment]
Thx a lot¡

**Comment by hatshu** [comment]
I have read the tutorial and I had the code like your manual, and the test error is still there :(

**Comment by adrianmcli** [comment]
Do you think you can upload your project to a repo and I'll take a look?

**Comment by adrianmcli** [comment]
Hmm, it looks like it might be related to #700, a Windows-specific issue. Either way, if you upload your project, I'll try it on my Mac just to make sure. I'll try to ping someone with a Windows computer for you, but most of the team is on holidays.

**Comment by hatshu** [comment]
ok i will do it

**Comment by hatshu** [comment]
https://github.com/hatshu/solidityPruebas

**Comment by adrianmcli** [comment]
Okay, I've run the tests and it works fine on my end (on a Mac). So I'm pretty sure this is a Windows problem. I'll ping someone on the team and hopefully they'll get back to you soon.

**Comment by hatshu** [comment]
Ok thx for your help. 

Happy holidays¡

**Comment by adrianmcli** [comment]
Are you using WSL and Windows together? Someone from the team mentioned that if you run all tthe commands under the same OS it should work.

**Comment by belenmartinsoltel** [comment]
im not using WSL :S

**Comment by adrianmcli** [comment]
@belenmartinsoltel can you explain your situation?

**Comment by belenmartinsoltel** [comment]
I have windows 10
visual studio with solidity extension (fran blanco) 
Truffle v5.0.0 (core: 5.0.0)
Solidity v0.5.0 (solc-js)
Node v10.15.0
ganache gui v1.2.2


I can compile with truffle compile
I can migrate with truffle migration
but I cant pass test becouse the error that said me on console :


TestAdoption
"before all" hook: prepare suite:
Error: Could not find artifacts for /D/DESARROLLO/Servicechain.git/servicechain/pet-shop-tutorial/contracts/Adoption.sol from any sources
at Resolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
at dependency_paths.forEach.dependency_path (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
at Array.forEach ()
at deployer.deploy.then (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
at C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
at process._tickCallback (internal/process/next_tick.js:68:7)



I have installed Docker on windows too. That was  for compiler error that said me when I tried to compile ( and did:  docker pull ethereum/solc:0.5.0 ) That was when I changed pragma solidity to 0.5.0.

Maybe is a issue with docker?

**Comment by belenmartinsoltel** [comment]
And I can see the web when I finished the tutorial, And I cant adopt pets¡¡¡ so its working, but test not passing, I have installed the Metacoin box and happends the same... :S

**Comment by belenmartinsoltel** [comment]
Sorry  I dont see that now I was with a other account -.- now Im using the labtop to work -.- Im hatshu XD

**Comment by belenmartinsoltel** [comment]
I was reading the https://github.com/trufflesuite/truffle/issues/700 and I see is like my problem, sounds like the bug appears again in version 5 :( Can be this?

**Comment by CruzMolina** [comment]
Thanks for following up on this @belenmartinsoltel (@hatshu) !

Haven't looked at this extensively, but based on your stack trace and the stack trace in #700, this looks like a path resolving issue (looks like your shell operating in the D:/ drive gets translated by truffle into /D/).

**Comment by belenmartinsoltel** [comment]
I have 2 pc's with windows 10, and happend on both... Now I have unboxing webpack with truffle, and happend the same with test on solidity, test on javascript go well.


PS C:\PROYECTOS\BlockChainDocs\servicechain.git\servicechain\webpack> truffle test
Using network 'development'.

Compiling .\contracts\ConvertLib.sol...
Compiling .\test\TestMetacoin.sol...


  TestMetacoin
    1) "before all" hook: prepare suite

  Contract: MetaCoin
    √ should put 10000 MetaCoin in the first account (110ms)
    √ should call a function that depends on a linked library (93ms)
    √ should send coin correctly (387ms)


  3 passing (10s)
  1 failing

  1) TestMetacoin
       "before all" hook: prepare suite:
     Error: Could not find artifacts for /C/PROYECTOS/BlockChainDocs/servicechain.git/servicechain/webpack/contracts/ConvertLib.sol from any sources
      at Resolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at TestResolver.require (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:17:1)
      at dependency_paths.forEach.dependency_path (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\belen\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by gnidan** [comment]
This should be fixed and will be released in our next patch. Thanks!

**Comment by belenmartinsoltel** [comment]
THX SO MUCH¡¡¡¡¡

**Comment by YXTR** [comment]
I also encountered this issue when I was studying the pet-shop tutorial (1/12/2019).
I'm using Windows 10 1809
Truffle v5.0.1 (core: 5.0.1)
Solidity v0.5.0 (solc-js)
Node v10.14.2

I can compile with truffle compile, and I can migrate with truffle migration, but when truffle test:

```
PS D:\Documents\Blockchain\pet-shop-tutorial> truffle test
Using network 'development'.

Compiling .\test\TestAdoption.sol...


  TestAdoption
    1) "before all" hook: prepare suite


  0 passing (6s)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     Error: Could not find artifacts for \D\Documents\Blockchain\pet-shop-tutorial\contracts\Adoption.sol from any sources
      at Resolver.require (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-resolver\index.js:37:1)
      at TestResolver.require (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at TestResolver.require (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testresolver.js:23:1)
      at dependency_paths.forEach.dependency_path (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:203:1)
      at Array.forEach (<anonymous>)
      at deployer.deploy.then (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\soliditytest.js:202:1)
      at C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deferredchain.js:20:1
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

It seems that the address `/D/.../pet-shop-tutorial/contracts/Adoption.sol ` has become to `\D\...\pet-shop-tutorial\contracts\Adoption.sol` after this release, but still the artifacts could not be found.

**Comment by Alexandre17220** [comment]
same error , very boring for tutorial..
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v11.8.0

**Comment by adrianmcli** [comment]
It seems like the issue is still persisting, let me see if I can get someone on the team with a Windows machine to test it.

**Comment by CnBDM-Su** [comment]
It seems like a WIN path problem. does anyone know how to use a absolute path in the import part. I guess maybe could solve this problem.

**Comment by cryptoads** [comment]
Same issue - watching for fix 👀

**Comment by marv311** [comment]
I have the same issue

**Comment by delerak** [comment]
I also have the same issue, I've tried messing with the pathing in the windows but it appears to be a Truffle framework issue that will need a fix on that end.

**Comment by adrianmcli** [comment]
@cryptoads @marv311 @delerak you guys are all on Windows machines?

**Comment by delerak** [comment]
Yep. I have a Linux laptop I'm going to use to finish the tutorial for my own desire to finish it.

**Comment by adrianmcli** [comment]
Looks like this might be related to https://github.com/trufflesuite/truffle/issues/1630. We should have a fix for that some time this week.

**Comment by marv311** [comment]
@adrianmcli Yes I am on a Windows 10 Machine

**Comment by cryptoads** [comment]
@adrianmcli  Yes, win10

**Comment by marv311** [comment]
@adrianmcli mine works now with the new upate

**Comment by adrianmcli** [comment]
@marv311 excellent! Can others in this thread also confirm?

**Comment by ani-mal** [comment]
I am having the same issue. I just started the tutorial this morning. 

#### Description 
Win 10 1809 
Truffle v5.0.20
Solidity v0.5.0
Node v11.6.0 
Web.js v1.0.0-beta.37

**Comment by Keegan-lee** [comment]
I am having the same issue

**Comment by wagneripjr** [comment]
I have the same issue here :(

**Comment by sergiocasero** [comment]
Same issue here :(

**Comment by adrianmcli** [comment]
The team is currently on a retreat right now, we'll try to look into this next week!

**Comment by cracki** [comment]
Same issue here :(

**Comment by LucaRossi02** [comment]
Same issue here

**Comment by cejensen-ra** [comment]
Same issue here too

**Comment by KadenZipfel** [comment]
Same issue still

**Comment by anildharni** [comment]
I am on windows 10.
test failed when I used truffle version 5.0.2.
Updated the truffle version 5.1.39 just to see if it changes anything and test passed. See if this helps.
